# -*- coding: utf-8 -*-
"""task1_data_collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hn-iRbk6Pk7c8TxUwTmI5HhWsWg8n0E0
"""

# task1_data_collection.py
# TrendPulse - Task 1: Fetch trending stories from HackerNews API

import requests
import time
import os
import json
from datetime import datetime

# Base URLs
TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"

# Header (as required)
headers = {"User-Agent": "TrendPulse/1.0"}

# Categories and keywords
categories = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["nfl", "nba", "fifa", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome"],
    "entertainment": ["movie", "film", "music", "netflix", "game", "book", "show", "award", "streaming"]
}

# Store collected stories
collected_stories = []

# Limit per category
CATEGORY_LIMIT = 25

# ---- STEP 1: FETCH TOP STORY IDS ----
try:
    response = requests.get(TOP_STORIES_URL, headers=headers)
    response.raise_for_status()
    top_ids = response.json()[:500]  # first 500 IDs
except Exception as e:
    print("Failed to fetch top stories:", e)
    exit()

# ---- STEP 2: FETCH STORY DETAILS & CATEGORIZE ----

# Track how many stories per category
category_counts = {cat: 0 for cat in categories}

# Current timestamp
collected_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# Loop through categories
for category, keywords in categories.items():
    print(f"Collecting {category} stories...")

    for story_id in top_ids:
        # Stop if category limit reached
        if category_counts[category] >= CATEGORY_LIMIT:
            break

        try:
            res = requests.get(ITEM_URL.format(story_id), headers=headers)
            res.raise_for_status()
            story = res.json()
        except Exception:
            print(f"Failed to fetch story ID {story_id}")
            continue

        # Skip if no title
        if not story or "title" not in story:
            continue

        title = story["title"].lower()

        # Check if title matches any keyword
        if any(keyword in title for keyword in keywords):

            # Extract required fields safely
            post = {
                "post_id": story.get("id"),
                "title": story.get("title"),
                "category": category,
                "score": story.get("score", 0),
                "num_comments": story.get("descendants", 0),
                "author": story.get("by", "unknown"),
                "collected_at": collected_time
            }

            collected_stories.append(post)
            category_counts[category] += 1

    # Sleep AFTER each category loop (as required)
    time.sleep(2)

# ---- STEP 3: SAVE TO JSON FILE ----

# Create data folder if it doesn't exist
os.makedirs("data", exist_ok=True)

# File name with date
today = datetime.now().strftime("%Y%m%d")
file_path = f"data/trends_{today}.json"

# Save JSON
with open(file_path, "w", encoding="utf-8") as f:
    json.dump(collected_stories, f, indent=2)

# Final output
print(f"\nCollected {len(collected_stories)} stories. Saved to {file_path}")