# -*- coding: utf-8 -*-
"""task3_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yTJX91SA-9b6YloNR2ISdJcQcoNC9nyq
"""

import requests
import time
import os
import json
from datetime import datetime

#Define API URL & Headers
BASE_URL="https://hacker-news.firebaseio.com/v0"
headers = {"User-Agent": "TrendPulse/1.0"}

# Category keyword mapping (case-insensitive)
CATEGORIES = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["nfl", "nba", "fifa", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome"],
    "entertainment": ["movie", "film", "music", "netflix", "game", "book", "show", "award", "streaming"]
}

#Assign a category based on keywords in title.
#Returns category name or None if no match found.

def assign_category(title):
    title_lower = title.lower()

    for category, keywords in CATEGORIES.items():
        for keyword in keywords:
            if keyword in title_lower:
                return category
    return None


# Step 1: Fetch top story IDs
try:
    response = requests.get(f"{BASE_URL}/topstories.json", headers=headers)
    response.raise_for_status()
    story_ids = response.json()[:500]  # first 500 IDs
except Exception as e:
    print("Error fetching top stories:", e)
    story_ids = []

# Store results
collected_data = []
category_count = {cat: 0 for cat in CATEGORIES}

MAX_PER_CATEGORY = 25
# Step 2: Process category-wise
for story_id in story_ids:

    try:
        url = f"{BASE_URL}/item/{story_id}.json"
        res = requests.get(url, headers=headers)

        if res.status_code != 200:
            continue

        story = res.json()

        if not story or "title" not in story:
            continue

        assigned_category = assign_category(story["title"])

        # Only proceed if category found
        if assigned_category and category_count[assigned_category] < MAX_PER_CATEGORY:

            data = {
                "post_id": story.get("id"),
                "title": story.get("title"),
                "category": assigned_category,
                "score": story.get("score", 0),
                "num_comments": story.get("descendants", 0),
                "author": story.get("by"),
                "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            }

            collected_data.append(data)
            category_count[assigned_category] += 1

    except Exception as e:
        print(f"Error fetching story {story_id}: {e}")
        continue

    # Stop when all categories filled
    if all(count >= MAX_PER_CATEGORY for count in category_count.values()):
        break

# Sleep once after processing
time.sleep(2)


# Step 3: Save data to JSON file
if not os.path.exists("data"):
    os.makedirs("data")

filename = f"data/trends_{datetime.now().strftime('%Y%m%d')}.json"

with open(filename, "w") as f:
    json.dump(collected_data, f, indent=4)


# Final output
print("\nTotal stories collected:", len(collected_data))
print("Saved file:", filename)