# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hn-iRbk6Pk7c8TxUwTmI5HhWsWg8n0E0
"""

# task1_data_collection.py
# TrendPulse - Task 1: Fetch trending stories from HackerNews API

import requests
import time
import os
import json
from datetime import datetime

# Base URLs
TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"

# Header (as required)
headers = {"User-Agent": "TrendPulse/1.0"}

# Categories and keywords
categories = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["nfl", "nba", "fifa", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome"],
    "entertainment": ["movie", "film", "music", "netflix", "game", "book", "show", "award", "streaming"]
}

# Store collected stories
collected_stories = []

# Limit per category
CATEGORY_LIMIT = 25

# ---- STEP 1: FETCH TOP STORY IDS ----
try:
    response = requests.get(TOP_STORIES_URL, headers=headers)
    response.raise_for_status()
    top_ids = response.json()[:500]  # first 500 IDs
except Exception as e:
    print("Failed to fetch top stories:", e)
    exit()

# ---- STEP 2: FETCH STORY DETAILS & CATEGORIZE ----

# Track how many stories per category
category_counts = {cat: 0 for cat in categories}

# Current timestamp
collected_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# Loop through categories
for category, keywords in categories.items():
    print(f"Collecting {category} stories...")

    for story_id in top_ids:
        # Stop if category limit reached
        if category_counts[category] >= CATEGORY_LIMIT:
            break

        try:
            res = requests.get(ITEM_URL.format(story_id), headers=headers)
            res.raise_for_status()
            story = res.json()
        except Exception:
            print(f"Failed to fetch story ID {story_id}")
            continue

        # Skip if no title
        if not story or "title" not in story:
            continue

        title = story["title"].lower()

        # Check if title matches any keyword
        if any(keyword in title for keyword in keywords):

            # Extract required fields safely
            post = {
                "post_id": story.get("id"),
                "title": story.get("title"),
                "category": category,
                "score": story.get("score", 0),
                "num_comments": story.get("descendants", 0),
                "author": story.get("by", "unknown"),
                "collected_at": collected_time
            }

            collected_stories.append(post)
            category_counts[category] += 1

    # Sleep AFTER each category loop (as required)
    time.sleep(2)

# ---- STEP 3: SAVE TO JSON FILE ----

# Create data folder if it doesn't exist
os.makedirs("data", exist_ok=True)

# File name with date
today = datetime.now().strftime("%Y%m%d")
file_path = f"data/trends_{today}.json"

# Save JSON
with open(file_path, "w", encoding="utf-8") as f:
    json.dump(collected_stories, f, indent=2)

# Final output
print(f"\nCollected {len(collected_stories)} stories. Saved to {file_path}")

# task2_data_processing.py
# TrendPulse - Task 2: Clean JSON data and save as CSV

import pandas as pd
import os
from datetime import datetime

# ---- STEP 1: LOAD JSON FILE ----

# Get today's date in YYYYMMDD format (same format used in Task 1)
today = datetime.now().strftime("%Y%m%d")

# File path
file_path = f"data/trends_{today}.json"

# Check if file exists
if not os.path.exists(file_path):
    print(f"File not found: {file_path}")
    exit()

# Load JSON into DataFrame
df = pd.read_json(file_path)

# Print initial row count
print(f"Loaded {len(df)} stories from {file_path}\n")


# ---- STEP 2: CLEAN THE DATA ----

# 1. Remove duplicates based on post_id
before = len(df)
df = df.drop_duplicates(subset="post_id")
print(f"After removing duplicates: {len(df)}")

# 2. Remove rows with missing critical values
df = df.dropna(subset=["post_id", "title", "score"])
print(f"After removing nulls: {len(df)}")

# 3. Convert data types
# Convert score and num_comments to integers
df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].fillna(0).astype(int)

# 4. Remove low-quality posts (score < 5)
df = df[df["score"] >= 5]
print(f"After removing low scores: {len(df)}")

# 5. Strip whitespace from title
df["title"] = df["title"].str.strip()


# ---- STEP 3: SAVE CLEAN DATA ----

# Output file path
output_path = "data/trends_clean.csv"

# Save to CSV
df.to_csv(output_path, index=False)

# Confirmation message
print(f"\nSaved {len(df)} rows to {output_path}\n")


# ---- SUMMARY: STORIES PER CATEGORY ----

print("Stories per category:")
category_counts = df["category"].value_counts()

for category, count in category_counts.items():
    print(f"  {category:<15} {count}")

# task3_analysis.py
# TrendPulse - Task 3: Data Analysis using Pandas & NumPy

import pandas as pd
import numpy as np
import os

# ---- STEP 1: LOAD DATA ----

file_path = "data/trends_clean.csv"

# Check if file exists
if not os.path.exists(file_path):
    print(f"File not found: {file_path}")
    exit()

# Load CSV into DataFrame
df = pd.read_csv(file_path)

# Print shape
print(f"Loaded data: {df.shape}\n")

# Print first 5 rows
print("First 5 rows:")
print(df.head(), "\n")

# Average score and comments (using Pandas)
avg_score = df["score"].mean()
avg_comments = df["num_comments"].mean()

print(f"Average score   : {int(avg_score):,}")
print(f"Average comments: {int(avg_comments):,}\n")


# ---- STEP 2: NUMPY ANALYSIS ----

print("--- NumPy Stats ---")

scores = df["score"].values

# NumPy calculations
mean_score = np.mean(scores)
median_score = np.median(scores)
std_score = np.std(scores)
max_score = np.max(scores)
min_score = np.min(scores)

print(f"Mean score   : {int(mean_score):,}")
print(f"Median score : {int(median_score):,}")
print(f"Std deviation: {int(std_score):,}")
print(f"Max score    : {max_score:,}")
print(f"Min score    : {min_score}\n")

# Category with most stories
category_counts = df["category"].value_counts()
top_category = category_counts.idxmax()
top_count = category_counts.max()

print(f"Most stories in: {top_category} ({top_count} stories)\n")

# Story with most comments
most_commented = df.loc[df["num_comments"].idxmax()]

print("Most commented story:")
print(f"\"{most_commented['title']}\" — {most_commented['num_comments']:,} comments\n")


# ---- STEP 3: ADD NEW COLUMNS ----

# Engagement = comments per upvote (avoid division by zero using +1)
df["engagement"] = df["num_comments"] / (df["score"] + 1)

# is_popular = score greater than average
df["is_popular"] = df["score"] > avg_score


# ---- STEP 4: SAVE UPDATED DATA ----

output_path = "data/trends_analysed.csv"

df.to_csv(output_path, index=False)

print(f"Saved to {output_path}")