# -*- coding: utf-8 -*-
"""task1_data_collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QSg6tVoUYJXQ8IGhUpB4gy1cTbdwhiuO
"""

import requests
import time
import os
import json
from datetime import datetime

#Define API URL & Headers
BASE_URL = "https://hacker-news.firebaseio.com/v0"
headers = {"User-Agent": "TrendPulse/1.0"}

# Category keyword mapping (case-insensitive)
CATEGORIES = {
    "technology": [
        "ai", "software", "tech", "code", "computer",
        "data", "cloud", "api", "gpu", "llm",
        "developer", "programming", "github",
        "open source", "show hn", "ask hn", "tool", "app"
    ],
    "worldnews": [
        "war", "government", "country", "president",
        "election", "climate", "attack", "global",
        "news", "policy", "china", "india", "usa"
    ],
    "sports": [
        "nfl", "nba", "fifa", "sport", "game",
        "team", "player", "league", "match",
        "cricket", "football", "tennis"
    ],
    "science": [
        "research", "study", "space", "physics",
        "biology", "discovery", "nasa",
        "science", "experiment", "quantum"
    ],
    "entertainment": [
        "movie", "film", "music", "netflix",
        "game", "book", "show", "stream",
        "tv", "youtube", "series"
    ]
}

#Assign a category based on keywords in title.
#Returns category name or None if no match found.

def assign_category(title):
    if not title:
        return None

    title_lower = title.lower()

    for category, keywords in CATEGORIES.items():
        for keyword in keywords:
            if keyword in title_lower:
                return category

    # 🔥 fallback (important)
    return "technology"

# Step 1: Fetch top story IDs
try:
    response = requests.get(f"{BASE_URL}/topstories.json", headers=headers)
    response.raise_for_status()
    story_ids = response.json()[:800]  # first 500 IDs
except Exception as e:
    print("Error fetching top stories:", e)
    story_ids = []